# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/miguel/Desktop/Linux_Unreal_Engine_5.4.4
GAMEPROJECTFILE =/home/miguel/Desktop/UE_Projects/Temporary_Folder_For_FMP/UEInventory.uproject

TARGETS = \
	DotNetPerforceLib-Linux-DebugGame  \
	DotNetPerforceLib-Linux-Shipping  \
	DotNetPerforceLib \
	EventLoopUnitTests-Linux-DebugGame  \
	EventLoopUnitTests-Linux-Shipping  \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame \
	UEInventory-Linux-DebugGame  \
	UEInventory-Linux-Shipping  \
	UEInventory \
	UEInventoryEditor-Linux-DebugGame  \
	UEInventoryEditor-Linux-Shipping  \
	UEInventoryEditor\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend UEInventoryEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug UEInventoryEditor-Linux-Debug


DotNetPerforceLib-Linux-DebugGame:
	 $(BUILD) DotNetPerforceLib Linux DebugGame  $(ARGS)

DotNetPerforceLib-Linux-Shipping:
	 $(BUILD) DotNetPerforceLib Linux Shipping  $(ARGS)

DotNetPerforceLib:
	 $(BUILD) DotNetPerforceLib Linux Development  $(ARGS)

EventLoopUnitTests-Linux-DebugGame:
	 $(BUILD) EventLoopUnitTests Linux DebugGame  $(ARGS)

EventLoopUnitTests-Linux-Shipping:
	 $(BUILD) EventLoopUnitTests Linux Shipping  $(ARGS)

EventLoopUnitTests:
	 $(BUILD) EventLoopUnitTests Linux Development  $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UEInventory-Linux-DebugGame:
	 $(PROJECTBUILD) UEInventory Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UEInventory-Linux-Shipping:
	 $(PROJECTBUILD) UEInventory Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UEInventory:
	 $(PROJECTBUILD) UEInventory Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UEInventoryEditor-Linux-DebugGame:
	 $(PROJECTBUILD) UEInventoryEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UEInventoryEditor-Linux-Shipping:
	 $(PROJECTBUILD) UEInventoryEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UEInventoryEditor:
	 $(PROJECTBUILD) UEInventoryEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
